import { jsPDF } from 'jspdf'

export const pdfService = {
  generateStatutoryPDF: (title: string, content: string, companyName: string) => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    
    // Header
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(companyName.toUpperCase(), pageWidth / 2, 20, { align: 'center' })
    
    doc.setDrawColor(0, 0, 0)
    doc.line(20, 25, pageWidth - 20, 25)
    
    // Title
    doc.setFontSize(14)
    doc.text(title.toUpperCase(), pageWidth / 2, 35, { align: 'center' })
    
    // Content
    doc.setFontSize(10)
    doc.setFont('times', 'normal')
    
    const splitText = doc.splitTextToSize(content, pageWidth - 40)
    doc.text(splitText, 20, 50)
    
    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.text(`Generated by Agentic Compliance OS | Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })
    }
    
    doc.save(`${title.replace(/\s+/g, '_')}_${companyName.replace(/\s+/g, '_')}.pdf`)
  }
}
