import { useState, useEffect } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { 
  FileText, 
  ArrowLeft, 
  ChevronLeft, 
  Save, 
  Download,
  Eye,
  Bot,
  CheckCircle2,
  ScrollText
} from 'lucide-react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import { useWorkflowStore } from '@/stores/workflow-store'
import { incorporationService } from '@/services/incorporation.service'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'

interface Director {
    id: string
    full_name: string
}

export default function MoaAoaStep() {
  const navigate = useNavigate()
  const workflow = useWorkflowStore()
  const [isProcessing, setIsProcessing] = useState(false)
  const [isSavingDraft, setIsSavingDraft] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [activeTab, setActiveTab] = useState<'moa' | 'aoa'>('moa')
  
  const [formData, setFormData] = useState({
    moa_content: '',
    aoa_content: '',
    proposed_name: ''
  })
  const [directors, setDirectors] = useState<Director[]>([])

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Fetch MOA/AOA data
        const moaResponse = await incorporationService.getMoaAoa()
        if (moaResponse && moaResponse.moa_aoa_data) {
          setFormData(moaResponse.moa_aoa_data)
        }

        // Fetch DIN data for Directors sync
        const dinResponse = await incorporationService.getDin()
        if (dinResponse && dinResponse.din_data && Array.isArray(dinResponse.din_data.directors)) {
          setDirectors(dinResponse.din_data.directors)
        }
      } catch (error) {
        console.error('Failed to fetch data:', error)
      }
    }
    fetchData()
  }, [])

  const handleGenerateAI = async () => {
    setIsGenerating(true)
    try {
      const response = await incorporationService.generateDrafts()
      setFormData(prev => ({
        ...prev,
        moa_content: response.moa_content,
        aoa_content: response.aoa_content
      }))
      toast.success('MOA & AOA Drafts generated by AI!')
    } catch (error) {
      toast.error('Failed to generate drafts.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleSaveDraft = async () => {
    setIsSavingDraft(true)
    try {
      await incorporationService.saveMoaAoa(formData)
      toast.success('Draft saved successfully!')
    } catch (error) {
      toast.error('Failed to save draft.')
    } finally {
      setIsSavingDraft(false)
    }
  }

  const handleDownload = (type: 'MOA' | 'AOA') => {
    const content = type === 'MOA' ? formData.moa_content : formData.aoa_content;
    const pdfContent = `%PDF-1.1\n(Official ${type} for ${formData.proposed_name || 'Company'})\n\n${content}`;
    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${type}_Draft.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(`${type} downloaded successfully!`);
  };

  const handleComplete = async () => {
    if (!formData.moa_content || !formData.aoa_content) {
      toast.error('Please generate drafts first.')
      return
    }

    setIsProcessing(true)
    try {
      await incorporationService.saveMoaAoa(formData)
      workflow.completeStep(4)
      toast.success('Step 4: MOA & AOA Drafting Completed!')
      navigate({ to: '/admin/compliance/incorporation' })
    } catch (error) {
      toast.error('Submission failed.')
    } finally {
      setIsProcessing(false)
    }
  }

  return (
    <div className='p-6 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500'>
      <div className='flex items-center justify-between'>
        <div className='flex items-center gap-3'>
          <Button variant='ghost' size='icon' onClick={() => navigate({ to: '/admin/compliance/incorporation' })}>
            <ArrowLeft className='h-5 w-5' />
          </Button>
          <div className='p-3 bg-blue-500/10 rounded-2xl'>
            <ScrollText className='h-8 w-8 text-blue-600' />
          </div>
          <div>
            <h1 className='text-2xl font-bold'>Step 4: MOA & AOA Drafting</h1>
            <p className='text-sm text-muted-foreground'>Constitutional documents drafting powered by Compliance AI.</p>
          </div>
        </div>
      </div>

      <div className='grid grid-cols-1 lg:grid-cols-12 gap-8'>
        <div className='lg:col-span-8 space-y-6'>
          <Card className='border-none shadow-2xl bg-slate-100/50 overflow-hidden'>
            <CardHeader className='border-b bg-white/80 backdrop-blur-sm sticky top-0 z-20'>
              <div className='flex flex-col md:flex-row md:items-center justify-between gap-4'>
                <Tabs defaultValue='moa' className='w-full md:w-[400px]' onValueChange={(v) => setActiveTab(v as any)}>
                  <TabsList className='grid w-full grid-cols-2'>
                    <TabsTrigger value='moa'>Memorandum (MOA)</TabsTrigger>
                    <TabsTrigger value='aoa'>Articles (AOA)</TabsTrigger>
                  </TabsList>
                </Tabs>
                <div className='flex gap-2'>
                   <Button variant='outline' size='sm' className='rounded-full' onClick={() => handleDownload(activeTab === 'moa' ? 'MOA' : 'AOA')}>
                      <Download className='h-4 w-4 mr-1' /> PDF
                   </Button>
                   <Button variant='outline' size='sm' className='rounded-full'>
                      <Eye className='h-4 w-4 mr-1' /> View
                   </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className='p-0 bg-white min-h-[600px] relative'>
              {!formData.moa_content ? (
                <div className='absolute inset-0 flex flex-col items-center justify-center space-y-4 bg-slate-50/80 backdrop-blur-sm z-10'>
                   <div className='p-4 bg-primary/10 rounded-full'>
                     <Bot className='h-12 w-12 text-primary animate-pulse' />
                   </div>
                   <div className='text-center'>
                     <p className='font-bold text-lg'>Legal Drafts Awaiting AI</p>
                     <p className='text-sm text-muted-foreground'>Click "Draft with AI" to generate the first version.</p>
                   </div>
                </div>
              ) : (
                <div className='p-12 font-serif text-slate-800 leading-relaxed max-w-3xl mx-auto border-x shadow-inner h-full animate-in fade-in zoom-in-95 duration-700'>
                   <div className='text-center mb-12 border-b-2 border-slate-900 pb-8'>
                      <h2 className='text-2xl font-bold uppercase tracking-widest'>
                        {activeTab === 'moa' ? 'Memorandum of Association' : 'Articles of Association'}
                      </h2>
                      <p className='mt-2 text-sm italic font-sans'>of</p>
                      <h3 className='text-xl font-bold mt-2 uppercase font-sans border-2 border-slate-900 p-2 inline-block'>
                        {formData.proposed_name || 'ALPHA TECH'} PRIVATE LIMITED
                      </h3>
                   </div>
                   
                   <div className='whitespace-pre-wrap text-sm text-justify leading-loose space-y-8'>
                      {activeTab === 'moa' ? (
                        <div className='space-y-8'>
                           <div>
                              <p className='font-bold'>I. The name of the company is {formData.proposed_name || 'ALPHA TECH'} PRIVATE LIMITED.</p>
                           </div>
                           <div>
                              <p className='font-bold'>II. The registered office of the company will be situated in the State of TAMIL NADU.</p>
                           </div>
                           <div className='space-y-4'>
                              <p className='font-bold'>III. (a) The objects to be pursued by the company on its incorporation are:</p>
                              <div className='pl-6 space-y-3'>
                                 <p>1. To carry on the business of Software development, AI implementation and IT services, digital transformation, and related technology consultancy.</p>
                                 <p>2. To provide consultancy in agentic compliance systems, automated corporate governance, and legal-tech solutions.</p>
                              </div>
                           </div>
                           
                           {/* Dynamic Subscription Clause */}
                           <div className='mt-24 pt-12 border-t-2 border-slate-200'>
                              <p className='text-[10px] uppercase font-bold mb-8 text-center italic'>Subscription Clause</p>
                              <div className='grid grid-cols-2 gap-x-20 gap-y-12'>
                                 {directors.length > 0 ? (
                                    directors.map((director, idx) => (
                                        <div key={director.id} className='space-y-12'>
                                            <div className='border-b border-slate-400 h-12 w-full italic text-slate-400 flex items-end pb-1 text-[10px]'>Signature of Subscriber {idx + 1}</div>
                                            <div>
                                                <p className='font-bold text-xs uppercase'>{director.full_name || `DIRECTOR ${idx + 1} NAME`}</p>
                                                <p className='text-[10px] text-slate-500'>Proposed Director / Subscriber</p>
                                            </div>
                                        </div>
                                    ))
                                 ) : (
                                    <div className='col-span-2 text-center text-[10px] text-slate-400 italic'>
                                        No directors found from Step 2. Using placeholders...
                                    </div>
                                 )}
                              </div>
                              <div className='mt-12 p-4 bg-slate-50 border border-dashed border-slate-300 text-center'>
                                 <p className='text-[10px] font-bold uppercase'>Witnessed By:</p>
                                 <div className='mt-4 border-b border-slate-400 w-48 mx-auto' />
                                 <p className='text-[9px] mt-1'>(Advocate / CS / CA)</p>
                              </div>
                           </div>
                        </div>
                      ) : (
                        <div className='text-justify'>
                           {formData.aoa_content || 'Articles content loading...'}
                        </div>
                      )}
                   </div>
                </div>
              )}
            </CardContent>
          </Card>

          <div className='flex justify-between gap-3 pt-4'>
            <Button variant='outline' className='gap-2' onClick={() => navigate({ to: '/admin/compliance/incorporation/run' })}>
              <ChevronLeft className='h-4 w-4' /> Back
            </Button>
            <div className='flex gap-3'>
              <Button variant='outline' className='gap-2' onClick={handleSaveDraft} disabled={isSavingDraft}>
                <Save className='h-4 w-4' /> {isSavingDraft ? 'Saving...' : 'Save Draft'}
              </Button>
              <Button 
                className='px-8 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 shadow-lg shadow-blue-500/20 text-white border-none'
                onClick={handleGenerateAI}
                disabled={isGenerating}
              >
                {isGenerating ? 'AI Writing...' : <><Bot className='mr-2 h-4 w-4' /> Draft with AI</>}
              </Button>
              <Button className='px-8' onClick={handleComplete} disabled={isProcessing || !formData.moa_content}>
                {isProcessing ? 'Finalizing...' : 'Finalize Step 4'}
              </Button>
            </div>
          </div>
        </div>

        <div className='lg:col-span-4 space-y-6'>
          <Card className='bg-blue-50/50 border-blue-100 shadow-none'>
            <CardHeader className='pb-2'>
              <CardTitle className='text-sm flex items-center gap-2 text-blue-800'>
                <Bot className='h-4 w-4' />
                Agent Insight
              </CardTitle>
            </CardHeader>
            <CardContent className='space-y-4 text-[11px] text-blue-900 leading-relaxed'>
               The MOA now dynamically includes all directors registered in Step 2. The Subscription Clause reflects the actual legal structure.
               <div className='space-y-2 pt-2'>
                  <div className='flex items-center gap-2'>
                    <CheckCircle2 className='h-3 w-3 text-green-500' />
                    <span>Dynamic Director Sync Active</span>
                  </div>
               </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
