/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSelectCompanyRouteImport } from './routes/(auth)/select-company'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminComplianceIncorporationIndexRouteImport } from './routes/_authenticated/admin/compliance/incorporation/index'
import { Route as AuthenticatedAdminComplianceIncorporationSpiceRouteImport } from './routes/_authenticated/admin/compliance/incorporation/spice'
import { Route as AuthenticatedAdminComplianceIncorporationRunRouteImport } from './routes/_authenticated/admin/compliance/incorporation/run'
import { Route as AuthenticatedAdminComplianceIncorporationPanTanRouteImport } from './routes/_authenticated/admin/compliance/incorporation/pan-tan'
import { Route as AuthenticatedAdminComplianceIncorporationMoaAoaRouteImport } from './routes/_authenticated/admin/compliance/incorporation/moa-aoa'
import { Route as AuthenticatedAdminComplianceIncorporationLaborRouteImport } from './routes/_authenticated/admin/compliance/incorporation/labor'
import { Route as AuthenticatedAdminComplianceIncorporationGstRouteImport } from './routes/_authenticated/admin/compliance/incorporation/gst'
import { Route as AuthenticatedAdminComplianceIncorporationDscRouteImport } from './routes/_authenticated/admin/compliance/incorporation/dsc'
import { Route as AuthenticatedAdminComplianceIncorporationDinRouteImport } from './routes/_authenticated/admin/compliance/incorporation/din'
import { Route as AuthenticatedAdminComplianceIncorporationCommencementRouteImport } from './routes/_authenticated/admin/compliance/incorporation/commencement'
import { Route as AuthenticatedAdminComplianceIncorporationCoiRouteImport } from './routes/_authenticated/admin/compliance/incorporation/coi'
import { Route as AuthenticatedAdminComplianceIncorporationBankRouteImport } from './routes/_authenticated/admin/compliance/incorporation/bank'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSelectCompanyRoute = authSelectCompanyRouteImport.update({
  id: '/(auth)/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationIndexRoute =
  AuthenticatedAdminComplianceIncorporationIndexRouteImport.update({
    id: '/admin/compliance/incorporation/',
    path: '/admin/compliance/incorporation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationSpiceRoute =
  AuthenticatedAdminComplianceIncorporationSpiceRouteImport.update({
    id: '/admin/compliance/incorporation/spice',
    path: '/admin/compliance/incorporation/spice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationRunRoute =
  AuthenticatedAdminComplianceIncorporationRunRouteImport.update({
    id: '/admin/compliance/incorporation/run',
    path: '/admin/compliance/incorporation/run',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationPanTanRoute =
  AuthenticatedAdminComplianceIncorporationPanTanRouteImport.update({
    id: '/admin/compliance/incorporation/pan-tan',
    path: '/admin/compliance/incorporation/pan-tan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationMoaAoaRoute =
  AuthenticatedAdminComplianceIncorporationMoaAoaRouteImport.update({
    id: '/admin/compliance/incorporation/moa-aoa',
    path: '/admin/compliance/incorporation/moa-aoa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationLaborRoute =
  AuthenticatedAdminComplianceIncorporationLaborRouteImport.update({
    id: '/admin/compliance/incorporation/labor',
    path: '/admin/compliance/incorporation/labor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationGstRoute =
  AuthenticatedAdminComplianceIncorporationGstRouteImport.update({
    id: '/admin/compliance/incorporation/gst',
    path: '/admin/compliance/incorporation/gst',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationDscRoute =
  AuthenticatedAdminComplianceIncorporationDscRouteImport.update({
    id: '/admin/compliance/incorporation/dsc',
    path: '/admin/compliance/incorporation/dsc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationDinRoute =
  AuthenticatedAdminComplianceIncorporationDinRouteImport.update({
    id: '/admin/compliance/incorporation/din',
    path: '/admin/compliance/incorporation/din',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationCommencementRoute =
  AuthenticatedAdminComplianceIncorporationCommencementRouteImport.update({
    id: '/admin/compliance/incorporation/commencement',
    path: '/admin/compliance/incorporation/commencement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationCoiRoute =
  AuthenticatedAdminComplianceIncorporationCoiRouteImport.update({
    id: '/admin/compliance/incorporation/coi',
    path: '/admin/compliance/incorporation/coi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceIncorporationBankRoute =
  AuthenticatedAdminComplianceIncorporationBankRouteImport.update({
    id: '/admin/compliance/incorporation/bank',
    path: '/admin/compliance/incorporation/bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/select-company': typeof authSelectCompanyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/compliance/incorporation/bank': typeof AuthenticatedAdminComplianceIncorporationBankRoute
  '/admin/compliance/incorporation/coi': typeof AuthenticatedAdminComplianceIncorporationCoiRoute
  '/admin/compliance/incorporation/commencement': typeof AuthenticatedAdminComplianceIncorporationCommencementRoute
  '/admin/compliance/incorporation/din': typeof AuthenticatedAdminComplianceIncorporationDinRoute
  '/admin/compliance/incorporation/dsc': typeof AuthenticatedAdminComplianceIncorporationDscRoute
  '/admin/compliance/incorporation/gst': typeof AuthenticatedAdminComplianceIncorporationGstRoute
  '/admin/compliance/incorporation/labor': typeof AuthenticatedAdminComplianceIncorporationLaborRoute
  '/admin/compliance/incorporation/moa-aoa': typeof AuthenticatedAdminComplianceIncorporationMoaAoaRoute
  '/admin/compliance/incorporation/pan-tan': typeof AuthenticatedAdminComplianceIncorporationPanTanRoute
  '/admin/compliance/incorporation/run': typeof AuthenticatedAdminComplianceIncorporationRunRoute
  '/admin/compliance/incorporation/spice': typeof AuthenticatedAdminComplianceIncorporationSpiceRoute
  '/admin/compliance/incorporation/': typeof AuthenticatedAdminComplianceIncorporationIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/select-company': typeof authSelectCompanyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/compliance/incorporation/bank': typeof AuthenticatedAdminComplianceIncorporationBankRoute
  '/admin/compliance/incorporation/coi': typeof AuthenticatedAdminComplianceIncorporationCoiRoute
  '/admin/compliance/incorporation/commencement': typeof AuthenticatedAdminComplianceIncorporationCommencementRoute
  '/admin/compliance/incorporation/din': typeof AuthenticatedAdminComplianceIncorporationDinRoute
  '/admin/compliance/incorporation/dsc': typeof AuthenticatedAdminComplianceIncorporationDscRoute
  '/admin/compliance/incorporation/gst': typeof AuthenticatedAdminComplianceIncorporationGstRoute
  '/admin/compliance/incorporation/labor': typeof AuthenticatedAdminComplianceIncorporationLaborRoute
  '/admin/compliance/incorporation/moa-aoa': typeof AuthenticatedAdminComplianceIncorporationMoaAoaRoute
  '/admin/compliance/incorporation/pan-tan': typeof AuthenticatedAdminComplianceIncorporationPanTanRoute
  '/admin/compliance/incorporation/run': typeof AuthenticatedAdminComplianceIncorporationRunRoute
  '/admin/compliance/incorporation/spice': typeof AuthenticatedAdminComplianceIncorporationSpiceRoute
  '/admin/compliance/incorporation': typeof AuthenticatedAdminComplianceIncorporationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/select-company': typeof authSelectCompanyRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/compliance/incorporation/bank': typeof AuthenticatedAdminComplianceIncorporationBankRoute
  '/_authenticated/admin/compliance/incorporation/coi': typeof AuthenticatedAdminComplianceIncorporationCoiRoute
  '/_authenticated/admin/compliance/incorporation/commencement': typeof AuthenticatedAdminComplianceIncorporationCommencementRoute
  '/_authenticated/admin/compliance/incorporation/din': typeof AuthenticatedAdminComplianceIncorporationDinRoute
  '/_authenticated/admin/compliance/incorporation/dsc': typeof AuthenticatedAdminComplianceIncorporationDscRoute
  '/_authenticated/admin/compliance/incorporation/gst': typeof AuthenticatedAdminComplianceIncorporationGstRoute
  '/_authenticated/admin/compliance/incorporation/labor': typeof AuthenticatedAdminComplianceIncorporationLaborRoute
  '/_authenticated/admin/compliance/incorporation/moa-aoa': typeof AuthenticatedAdminComplianceIncorporationMoaAoaRoute
  '/_authenticated/admin/compliance/incorporation/pan-tan': typeof AuthenticatedAdminComplianceIncorporationPanTanRoute
  '/_authenticated/admin/compliance/incorporation/run': typeof AuthenticatedAdminComplianceIncorporationRunRoute
  '/_authenticated/admin/compliance/incorporation/spice': typeof AuthenticatedAdminComplianceIncorporationSpiceRoute
  '/_authenticated/admin/compliance/incorporation/': typeof AuthenticatedAdminComplianceIncorporationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/select-company'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center/'
    | '/settings/'
    | '/users/'
    | '/admin/compliance/incorporation/bank'
    | '/admin/compliance/incorporation/coi'
    | '/admin/compliance/incorporation/commencement'
    | '/admin/compliance/incorporation/din'
    | '/admin/compliance/incorporation/dsc'
    | '/admin/compliance/incorporation/gst'
    | '/admin/compliance/incorporation/labor'
    | '/admin/compliance/incorporation/moa-aoa'
    | '/admin/compliance/incorporation/pan-tan'
    | '/admin/compliance/incorporation/run'
    | '/admin/compliance/incorporation/spice'
    | '/admin/compliance/incorporation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/select-company'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings'
    | '/users'
    | '/admin/compliance/incorporation/bank'
    | '/admin/compliance/incorporation/coi'
    | '/admin/compliance/incorporation/commencement'
    | '/admin/compliance/incorporation/din'
    | '/admin/compliance/incorporation/dsc'
    | '/admin/compliance/incorporation/gst'
    | '/admin/compliance/incorporation/labor'
    | '/admin/compliance/incorporation/moa-aoa'
    | '/admin/compliance/incorporation/pan-tan'
    | '/admin/compliance/incorporation/run'
    | '/admin/compliance/incorporation/spice'
    | '/admin/compliance/incorporation'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/select-company'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/compliance/incorporation/bank'
    | '/_authenticated/admin/compliance/incorporation/coi'
    | '/_authenticated/admin/compliance/incorporation/commencement'
    | '/_authenticated/admin/compliance/incorporation/din'
    | '/_authenticated/admin/compliance/incorporation/dsc'
    | '/_authenticated/admin/compliance/incorporation/gst'
    | '/_authenticated/admin/compliance/incorporation/labor'
    | '/_authenticated/admin/compliance/incorporation/moa-aoa'
    | '/_authenticated/admin/compliance/incorporation/pan-tan'
    | '/_authenticated/admin/compliance/incorporation/run'
    | '/_authenticated/admin/compliance/incorporation/spice'
    | '/_authenticated/admin/compliance/incorporation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSelectCompanyRoute: typeof authSelectCompanyRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/select-company': {
      id: '/(auth)/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof authSelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/': {
      id: '/_authenticated/admin/compliance/incorporation/'
      path: '/admin/compliance/incorporation'
      fullPath: '/admin/compliance/incorporation/'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/spice': {
      id: '/_authenticated/admin/compliance/incorporation/spice'
      path: '/admin/compliance/incorporation/spice'
      fullPath: '/admin/compliance/incorporation/spice'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationSpiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/run': {
      id: '/_authenticated/admin/compliance/incorporation/run'
      path: '/admin/compliance/incorporation/run'
      fullPath: '/admin/compliance/incorporation/run'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/pan-tan': {
      id: '/_authenticated/admin/compliance/incorporation/pan-tan'
      path: '/admin/compliance/incorporation/pan-tan'
      fullPath: '/admin/compliance/incorporation/pan-tan'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationPanTanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/moa-aoa': {
      id: '/_authenticated/admin/compliance/incorporation/moa-aoa'
      path: '/admin/compliance/incorporation/moa-aoa'
      fullPath: '/admin/compliance/incorporation/moa-aoa'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationMoaAoaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/labor': {
      id: '/_authenticated/admin/compliance/incorporation/labor'
      path: '/admin/compliance/incorporation/labor'
      fullPath: '/admin/compliance/incorporation/labor'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationLaborRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/gst': {
      id: '/_authenticated/admin/compliance/incorporation/gst'
      path: '/admin/compliance/incorporation/gst'
      fullPath: '/admin/compliance/incorporation/gst'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationGstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/dsc': {
      id: '/_authenticated/admin/compliance/incorporation/dsc'
      path: '/admin/compliance/incorporation/dsc'
      fullPath: '/admin/compliance/incorporation/dsc'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationDscRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/din': {
      id: '/_authenticated/admin/compliance/incorporation/din'
      path: '/admin/compliance/incorporation/din'
      fullPath: '/admin/compliance/incorporation/din'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationDinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/commencement': {
      id: '/_authenticated/admin/compliance/incorporation/commencement'
      path: '/admin/compliance/incorporation/commencement'
      fullPath: '/admin/compliance/incorporation/commencement'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationCommencementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/coi': {
      id: '/_authenticated/admin/compliance/incorporation/coi'
      path: '/admin/compliance/incorporation/coi'
      fullPath: '/admin/compliance/incorporation/coi'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationCoiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance/incorporation/bank': {
      id: '/_authenticated/admin/compliance/incorporation/bank'
      path: '/admin/compliance/incorporation/bank'
      fullPath: '/admin/compliance/incorporation/bank'
      preLoaderRoute: typeof AuthenticatedAdminComplianceIncorporationBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminComplianceIncorporationBankRoute: typeof AuthenticatedAdminComplianceIncorporationBankRoute
  AuthenticatedAdminComplianceIncorporationCoiRoute: typeof AuthenticatedAdminComplianceIncorporationCoiRoute
  AuthenticatedAdminComplianceIncorporationCommencementRoute: typeof AuthenticatedAdminComplianceIncorporationCommencementRoute
  AuthenticatedAdminComplianceIncorporationDinRoute: typeof AuthenticatedAdminComplianceIncorporationDinRoute
  AuthenticatedAdminComplianceIncorporationDscRoute: typeof AuthenticatedAdminComplianceIncorporationDscRoute
  AuthenticatedAdminComplianceIncorporationGstRoute: typeof AuthenticatedAdminComplianceIncorporationGstRoute
  AuthenticatedAdminComplianceIncorporationLaborRoute: typeof AuthenticatedAdminComplianceIncorporationLaborRoute
  AuthenticatedAdminComplianceIncorporationMoaAoaRoute: typeof AuthenticatedAdminComplianceIncorporationMoaAoaRoute
  AuthenticatedAdminComplianceIncorporationPanTanRoute: typeof AuthenticatedAdminComplianceIncorporationPanTanRoute
  AuthenticatedAdminComplianceIncorporationRunRoute: typeof AuthenticatedAdminComplianceIncorporationRunRoute
  AuthenticatedAdminComplianceIncorporationSpiceRoute: typeof AuthenticatedAdminComplianceIncorporationSpiceRoute
  AuthenticatedAdminComplianceIncorporationIndexRoute: typeof AuthenticatedAdminComplianceIncorporationIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminComplianceIncorporationBankRoute:
    AuthenticatedAdminComplianceIncorporationBankRoute,
  AuthenticatedAdminComplianceIncorporationCoiRoute:
    AuthenticatedAdminComplianceIncorporationCoiRoute,
  AuthenticatedAdminComplianceIncorporationCommencementRoute:
    AuthenticatedAdminComplianceIncorporationCommencementRoute,
  AuthenticatedAdminComplianceIncorporationDinRoute:
    AuthenticatedAdminComplianceIncorporationDinRoute,
  AuthenticatedAdminComplianceIncorporationDscRoute:
    AuthenticatedAdminComplianceIncorporationDscRoute,
  AuthenticatedAdminComplianceIncorporationGstRoute:
    AuthenticatedAdminComplianceIncorporationGstRoute,
  AuthenticatedAdminComplianceIncorporationLaborRoute:
    AuthenticatedAdminComplianceIncorporationLaborRoute,
  AuthenticatedAdminComplianceIncorporationMoaAoaRoute:
    AuthenticatedAdminComplianceIncorporationMoaAoaRoute,
  AuthenticatedAdminComplianceIncorporationPanTanRoute:
    AuthenticatedAdminComplianceIncorporationPanTanRoute,
  AuthenticatedAdminComplianceIncorporationRunRoute:
    AuthenticatedAdminComplianceIncorporationRunRoute,
  AuthenticatedAdminComplianceIncorporationSpiceRoute:
    AuthenticatedAdminComplianceIncorporationSpiceRoute,
  AuthenticatedAdminComplianceIncorporationIndexRoute:
    AuthenticatedAdminComplianceIncorporationIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSelectCompanyRoute: authSelectCompanyRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
